In [1]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [2]:
df = pd.read_csv('C:/Shradda/loan_train.csv')
df.head()

Principal  terms effective_date   due_date  age             education  \
0       1000     30       9/8/2016  10/7/2016   45  High School or Below   
1       1000     30       9/8/2016  10/7/2016   33              Bechalor   
2       1000     15       9/8/2016  9/22/2016   27               college   
3       1000     30       9/9/2016  10/8/2016   28               college   
4       1000     30       9/9/2016  10/8/2016   29               college   

   Gender  
0    male  
1  female  
2    male  
3  female  
4    male

In [3]:
df.shape

(346, 7)

In [4]:
df['due_date'] = pd.to_datetime(df['due_date'])
df['effective_date'] = pd.to_datetime(df['effective_date'])

In [5]:
df.head()

Principal  terms effective_date   due_date  age             education  \
0       1000     30     2016-09-08 2016-10-07   45  High School or Below   
1       1000     30     2016-09-08 2016-10-07   33              Bechalor   
2       1000     15     2016-09-08 2016-09-22   27               college   
3       1000     30     2016-09-09 2016-10-08   28               college   
4       1000     30     2016-09-09 2016-10-08   29               college   

   Gender  
0    male  
1  female  
2    male  
3  female  
4    male

In [9]:
df['Gender'].replace(to_replace=['male','female'], value=[0,1],inplace=True)
df.head()

Principal  terms effective_date   due_date  age             education  \
0       1000     30     2016-09-08 2016-10-07   45  High School or Below   
1       1000     30     2016-09-08 2016-10-07   33              Bechalor   
2       1000     15     2016-09-08 2016-09-22   27               college   
3       1000     30     2016-09-09 2016-10-08   28               college   
4       1000     30     2016-09-09 2016-10-08   29               college   

   Gender  
0       0  
1       1  
2       0  
3       1  
4       0

In [10]:
df[['Principal','terms','age','Gender','education']].head()

Principal  terms  age  Gender             education
0       1000     30   45       0  High School or Below
1       1000     30   33       1              Bechalor
2       1000     15   27       0               college
3       1000     30   28       1               college
4       1000     30   29       0               college

In [14]:
Feature = df[['Principal','terms','age']]
Feature = pd.concat([Feature,pd.get_dummies(df['education'])], axis=1)
Feature.drop(['Master or Above'], axis = 1,inplace=True)
Feature.head()

Principal  terms  age  Bechalor  High School or Below  college
0       1000     30   45         0                     1        0
1       1000     30   33         1                     0        0
2       1000     15   27         0                     0        1
3       1000     30   28         0                     0        1
4       1000     30   29         0                     0        1

In [15]:
X = Feature
X[0:5]

Principal  terms  age  Bechalor  High School or Below  college
0       1000     30   45         0                     1        0
1       1000     30   33         1                     0        0
2       1000     15   27         0                     0        1
3       1000     30   28         0                     0        1
4       1000     30   29         0                     0        1

In [17]:
y = df['Gender'].values
y[0:5]

array([0, 1, 0, 1, 0], dtype=int64)

In [18]:
X= preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 0.51578458,  0.92071769,  2.33152555, -0.38170062,  1.13639374,
        -0.86968108],
       [ 0.51578458,  0.92071769,  0.34170148,  2.61985426, -0.87997669,
        -0.86968108],
       [ 0.51578458, -0.95911111, -0.65321055, -0.38170062, -0.87997669,
         1.14984679],
       [ 0.51578458,  0.92071769, -0.48739188, -0.38170062, -0.87997669,
         1.14984679],
       [ 0.51578458,  0.92071769, -0.3215732 , -0.38170062, -0.87997669,
         1.14984679]])

Knn

In [19]:
df.columns

Index(['Principal', 'terms', 'effective_date', 'due_date', 'age', 'education',
       'Gender'],
      dtype='object')

In [22]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.3)

In [23]:
classifier = KNeighborsClassifier(n_neighbors=3)
model=classifier.fit(X_train, Y_train)
y_pred = model.predict(X_test)

In [24]:
# Accuracy score
from sklearn.metrics import accuracy_score
knn_res=accuracy_score(y_pred,Y_test)
print('accuracy is',knn_res)

accuracy is 0.7788461538461539


# Decision Tree

In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


In [26]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.3)

In [27]:
classifier = DecisionTreeClassifier()
classifier.fit(X_train, Y_train)
y_pred = classifier.predict(X_test)


In [28]:
from sklearn.metrics import accuracy_score
dt_res=accuracy_score(y_pred,Y_test)
print('accuracy is',dt_res)

accuracy is 0.7307692307692307


# SVM

In [29]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [30]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.3)

In [31]:
classifier = SVC()
classifier.fit(X_train, Y_train)
y_pred = classifier.predict(X_test)

In [32]:
from sklearn.metrics import accuracy_score
svm_res=accuracy_score(y_pred,Y_test)
print('accuracy is',svm_res)

accuracy is 0.8269230769230769


# Logistic REgression

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
log=LogisticRegression()
model=log.fit(X_train,Y_train)
y_pred=model.predict(X_test)


In [35]:
from sklearn.metrics import accuracy_score
svm_res=accuracy_score(y_pred,Y_test)
print('accuracy is',svm_res)

accuracy is 0.8269230769230769


# Model Evaluation using Test set

In [36]:
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss

In [37]:
df2=pd.read_csv('C:/Shradda/loan_test.csv')

In [38]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [39]:
print(classification_report(y_pred,Y_test))
print(confusion_matrix(Y_test, y_pred))


              precision    recall  f1-score   support

           0       1.00      0.83      0.91       104
           1       0.00      0.00      0.00         0

    accuracy                           0.83       104
   macro avg       0.50      0.41      0.45       104
weighted avg       1.00      0.83      0.91       104

[[86  0]
 [18  0]]


C:\Users\Laptop-Kini\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
